name: Test

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [12, 14]
        os: [ubuntu-18.04, ubuntu-20.04]

    name: Node ${{ matrix.node }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn_cache
        run: echo "::set-output name=YARN_CACHE_DIR::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn_cache.outputs.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn

      - name: Tests
        run: yarn run test
